#!/bin/bash
# Bash lab 3

# using the which command to check if lxd is already installed on the system
which lxd >/dev/null
if [ $? -ne 0 ]; then
	# installing lxd
	echo "we  might need to enter our password to install LXD."
	sudo snap install lxd
	if [ $? -ne 0 ]; then
	#failed to install lxd - exit with an error message and status
		echo "Failed to install lxd software."
		exit 1
	fi
else
echo "1: Installing LXD in the virtual machine"
echo "##########"
echo "LXD is already set up in the virtual machine"
fi
echo "##########"
echo "Step2. Running lxbr0 in the vm"
echo "##########"
#running lxbr0 in the vm using lxd init --auto
ip a | grep -w "lxdbr0" > /dev/null
if [ $? -ne 0 ]; then
	lxd init --auto
	echo "Output=lxdbr0 is created" 
fi
echo "###end###"
